spring:
  data:
    mongodb:
      database: library
      port: 0
  mongodb:
    embedded:
      version: 3.5.5

mongock:
#  runner-type: InitializingBean
#  http://localhost:8080/webjars/jquery/3.5.1/jquery.min.js
  change-logs-scan-package:
    - ru.otus.spring.kolychev.library.mongock.changelog
