spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
#      mode: never
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
#      ddl-auto: create

    properties:
      hibernate:
#        enable_lazy_load_no_trans: true
        format_sql: true

    show-sql: true

  main:
    allow-circular-references: true
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true