DROP TABLE IF EXISTS books_authors;
DROP TABLE IF EXISTS books_genres;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS comments;

CREATE TABLE genres
(
    id    bigint generated by default as identity,
    title varchar(255),

    primary key (id)

);

CREATE TABLE authors
(
    id   bigint generated by default as identity,
    name varchar(255),

    primary key (id)
);

CREATE TABLE books
(
    id    bigint generated by default as identity,
    title varchar(255),

    primary key (id)
);

create table comments
(
    id      bigint generated by default as identity,
    content varchar(255),
    book_id bigint,

    primary key (id),
    foreign key (book_id) references books (id)
);

CREATE TABLE books_genres
(
    book_id  bigint not null,
    genre_id bigint not null,

    foreign key (genre_id) references genres (id),
    foreign key (book_id) references books (id)
);

CREATE TABLE books_authors
(
    book_id   bigint not null,
    author_id bigint not null,

    foreign key (author_id) references authors (id),
    foreign key (book_id) references books (id)
);